model: "ContextNet"
sample_rate: 16000
repeat: &repeat 5
dropout: &dropout 0.0
rnn_dropout: &rnn_dropout 0.0
stride: &stride 1


AudioToTextDataLayer:
    max_duration: 16.7
    trim_silence: true

    train:
        shuffle: true

    eval:
        shuffle: false
        max_duration: null

AudioToMelSpectrogramPreprocessor:
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    normalize: "per_feature"
    n_fft: 512
    features: 80
    dither: 0.00001
    pad_to: 16
    stft_conv: false

SpectrogramAugmentation:
    freq_masks: 2
    time_masks: 10
    freq_width: 27
    time_width: 0.05

ContextNetEncoder:
    activation: "relu"
    conv_mask: true

    jasper:
        -   filters: 128
            repeat: 1
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: false
            separable: true
            se: true
            se_context_size: -1

        -   filters: 128
            repeat: *repeat
            kernel: [11]
            stride: [2]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1
            stride_last: true
            residual_mode: "stride_add"

        -   filters: 128
            repeat: *repeat
            kernel: [13]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 128
            repeat: *repeat
            kernel: [15]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 128
            repeat: *repeat
            kernel: [17]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 128
            repeat: *repeat
            kernel: [19]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 128
            repeat: *repeat
            kernel: [21]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 128
            repeat: *repeat
            kernel: [25]
            stride: [*stride]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1
            stride_last: true
            residual_mode: "stride_add"

        -   filters: 128
            repeat: *repeat
            kernel: [27]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 128
            repeat: *repeat
            kernel: [29]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 128
            repeat: *repeat
            kernel: [31]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 256
            repeat: *repeat
            kernel: [33]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 256
            repeat: *repeat
            kernel: [35]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 256
            repeat: *repeat
            kernel: [37]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 256
            repeat: *repeat
            kernel: [39]
            stride: [*stride]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1
            stride_last: true
            residual_mode: "stride_add"

        -   filters: 256
            repeat: *repeat
            kernel: [41]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 256
            repeat: *repeat
            kernel: [43]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 256
            repeat: *repeat
            kernel: [45]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 256
            repeat: *repeat
            kernel: [47]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 256
            repeat: *repeat
            kernel: [49]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 256
            repeat: *repeat
            kernel: [51]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 256
            repeat: *repeat
            kernel: [53]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: &enc_hidden 320
            repeat: 1
            kernel: [55]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: false
            separable: true
            se: true
            se_context_size: -1

RNNTDecoder:
    normalization_mode: null

    rnnt:
        pred_hidden: &dec_hidden 640
        pred_rnn_layers: 1
        dropout: *rnn_dropout

RNNTJoint:
    rnnt:
        joint_hidden: 640
        encoder_hidden: *enc_hidden
        pred_hidden: *dec_hidden
        dropout: *rnn_dropout

labels: [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
         "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "'"]
