model: "ContextNet"
sample_rate: 16000
repeat: &repeat 5
dropout: &dropout 0.00
rnn_dropout: &rnn_dropout 0.00
stride: &stride 2


AudioToTextDataLayer:
    max_duration: 18.37
    trim_silence: true

    train:
        shuffle: true

    eval:
        shuffle: false
        max_duration: null

AudioToMelSpectrogramPreprocessor:
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    normalize: "per_feature"
    n_fft: 512
    features: 80
    dither: 0.00001
    pad_to: 16
    stft_conv: false

SpectrogramAugmentation:
    freq_masks: 2
    time_masks: 10
    freq_width: 27
    time_width: 0.05

ContextNetEncoder:
    activation: "swish"
    conv_mask: true

    jasper:
        -   filters: 192
            repeat: 1
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: false
            separable: true
            se: true
            se_context_size: -1

        -   filters: 192
            repeat: *repeat
            kernel: [5]
            stride: [2]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1
            stride_last: true
            residual_mode: "stride_add"

        -   filters: 192
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 192
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 192
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 192
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 192
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 192
            repeat: *repeat
            kernel: [5]
            stride: [*stride]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1
            stride_last: true
            residual_mode: "stride_add"

        -   filters: 192
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 192
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 192
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 384
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 384
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 384
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 384
            repeat: *repeat
            kernel: [5]
            stride: [*stride]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1
            stride_last: true
            residual_mode: "stride_add"

        -   filters: 384
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 384
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 384
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 384
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 384
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 384
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: 384
            repeat: *repeat
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: *dropout
            residual: true
            separable: true
            se: true
            se_context_size: -1

        -   filters: &enc_hidden 480
            repeat: 1
            kernel: [5]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: false
            separable: true
            se: true
            se_context_size: -1

RNNTDecoder:
    normalization_mode: null
    random_state_sampling: true

    rnnt:
        pred_hidden: &dec_hidden 640
        pred_rnn_layers: 1
        dropout: *rnn_dropout
        t_max: 210

RNNTJoint:
    preserve_memory: false
    softmax: false

    rnnt:
        joint_hidden: 640
        encoder_hidden: *enc_hidden
        pred_hidden: *dec_hidden
        dropout: *rnn_dropout

labels: [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
         "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "'"]
